site_name: Machine Learning
site_author: Sandmann, H.
site_url: https://hsandmann.github.io/ml
repo_url: https://github.com/hsandmann/ml
repo_name: hsandmann/ml

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  logo: assets/images/logo.png

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - neoteroi.timeline
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables


plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: insper/ann-dl
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - search
  - minify:
      minify_html: true
  - badges
  - markdown-exec
  - mkdocs-pdf
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.min.css
  - assets/stylesheets/neoteroi-timeline.css
  - assets/stylesheets/extra.css


nav:

  - 2025.2: ./versions/2025.2/index.md
  - Classes:
    - 1. Concepts:
      - 1.1. Machine Learning: ./classes/concepts/ml/index.md
      - 1.2. KDD: ./classes/concepts/kdd/index.md
      - 1.3. Data: ./classes/concepts/data/index.md
      - 1.4. Exercise: ./classes/concepts/exercise/index.md
    - 2. Decision Tree: ./classes/decision_tree/index.md
    - 3. Preprocessing: ./classes/preprocessing/index.md
    - 4. KNN: ./classes/knn/index.md
    - 5. K-Means: ./classes/kmeans/index.md
    - 6. Metrics and Evaluation:
      - 6.1. Classification: ./classes/metrics/classification/index.md
      - 6.2. Regression: ./classes/metrics/regression/index.md
      - 6.3. Exercise: ./classes/metrics/exercise/index.md
    - 7. Random Forest: ./classes/random_forest/index.md
    - 8. Gradient boosting: ./classes/gradient_boosting/index.md
    - 9. SVM: ./classes/svm/index.md
    - 10. Page Rank: ./classes/page-rank/index.md
    - 11. PySpark: ./classes/pyspark/index.md
    - 12. Neural Networks:
      - 12.1. Perceptron: ./classes/neural_network/perceptron/index.md
      - 12.2. MLP: ./classes/neural_network/mlp/index.md
      - 12.5. Exercise: ./classes/neural_network/exercise/index.md

  - Projects:
    - Project I: ./versions/2025.2/projects/1/index.md
    - Project II: ./versions/2025.2/projects/2/index.md

  - Versions:
    - 2025.2: ./versions/2025.2/index.md
